### ISSUE TITLE
No longer builds with current version of gotk4 v0.0.5

### ISSUE THREAD

**Issue by kendellfab** [diamondburned/gotk4-sourceview#2]
Errors when building:

../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220417102232-8ef402a7d0b2/gtksource/v5/gtksourcebuffer.go:73:22: undefined: externglib.GoPrivateFromObject
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220417102232-8ef402a7d0b2/gtksource/v5/gtksourcegutterrenderer.go:213:22: undefined: externglib.GoPrivateFromObject
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220417102232-8ef402a7d0b2/gtksource/v5/gtksourcegutterrenderer.go:235:22: undefined: externglib.GoPrivateFromObject
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220417102232-8ef402a7d0b2/gtksource/v5/gtksourcegutterrenderer.go:247:22: undefined: externglib.GoPrivateFromObject
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220417102232-8ef402a7d0b2/gtksource/v5/gtksourcegutterrenderer.go:261:22: undefined: externglib.GoPrivateFromObject
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220417102232-8ef402a7d0b2/gtksource/v5/gtksourcegutterrenderer.go:275:22: undefined: externglib.GoPrivateFromObject
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220417102232-8ef402a7d0b2/gtksource/v5/gtksourcegutterrenderer.go:283:22: undefined: externglib.GoPrivateFromObject
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220417102232-8ef402a7d0b2/gtksource/v5/gtksourcegutterrenderer.go:305:22: undefined: externglib.GoPrivateFromObject
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220417102232-8ef402a7d0b2/gtksource/v5/gtksourcegutterrenderer.go:321:22: undefined: externglib.GoPrivateFromObject
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220417102232-8ef402a7d0b2/gtksource/v5/gtksourceindenter.go:86:22: undefined: externglib.GoPrivateFromObject
../../../go/pkg/mod/github.com/diamondburned/gotk4-sourceview/pkg@v0.0.0-20220417102232-8ef402a7d0b2/gtksource/v5/gtksourceindenter.go:86:22: too many errors

**Comment by diamondburned** [comment]
This might need to be `go generate`'d again.

**Comment by kendellfab** [comment]
Sorry, I got wrapped up in some other things, and forgot to check back in on this. With regards to an existing project with a go.mod, how do I regenerate this project?

**Comment by diamondburned** [comment]
I can do that right now. The project is quite outdated compared to other gotk4-based repositories anyway.

**Comment by diamondburned** [comment]
Huh, short commit hashes (7 chars) stopped working at all for Nixpkgs, so the previous version lock is now invalid.

**Comment by diamondburned** [comment]
Fixed in bb7be44b538695900fb58f91f32020be6613ba3d.
